.github/release.yml

We want to provide consistent and comprehensive release notes when making
a release. Github supports generating draft release notes based on labels
attached to PRs to make this simpler.
- Add .github/release.yml with SemVer based release notes sections.
When creating a release, Github should populate the release notes based on the
PRs that have been merged since the last release and group them based on their
labels.
None.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Add .github/release.yml to automate drafting release notes

---

Sources/OpenAPIRuntime/Deprecated/Deprecated.swift

Unfortunately, as part of landing https://github.com/apple/swift-openapi-generator/issues/43, I made a mistake during backwards compatibility testing and forgot to add a few deprecated methods still used by generator 0.1.0.
That means that generator 0.1.0 doesn't work with runtime 0.1.1, currently.
This PR reintroduces them, so that generator 0.1.0 can work with a hotfix 0.1.2 again.
Re-added a few missing deprecated methods on Converter.
Someone using generator 0.1.0 with the latest runtime library (e.g. if they locked their generator version to 0.1.0 but didn't lock their runtime version) will have the generated code compiling again with runtime 0.1.2 (once this fix is landed).
Checked locally by actually checking our the different tags of runtime and generator and built them together.

[Fix] Re-introduce deprecated methods

---

Sources/OpenAPIRuntime/Conversion/Converter+Common.swift
Sources/OpenAPIRuntime/Conversion/Converter+Server.swift

Found two regressions with the signature of two of the ~50 converter helper methods:
- optional request body of type data
- required header fields of type JSON
Fixed up these signatures.
Now a project which has both can build.
Used a test project for finding and fixing these. We should think about increasing the integration test coverage, and run it on runtime PRs.

[Fix] Fix two regressions in Converter

---

docker/Dockerfile
scripts/run-integration-test.sh
scripts/soundness.sh

We want to make sure that we don't unknowingly introduce changes in the runtime
that break the generator, which relies on its SPI.
We have an package in a subdirectory in the generator repo that we can be used
as an integration test to gate changes to the various repos in Swift OpenAPI
project, including the runtime package.
The generator repo also contains a script that can be used to clone the
integration test package and use `swift package edit` to override a dependency
to check it still functions with the proposed changes.
- Bring in the `run-integraton-test.sh` script from the generator repo.
- Run this script as part of the soundness pipeline.
On each pull request, the integration test package will be built with the
changes proposed in the pull request.
The CI pipeline for this PR …

Add integration test CI check

---

Package.swift
Sources/OpenAPIRuntime/Conversion/Converter+Client.swift

Reduce deployment target by 3 versions to gain more adoption.
- Reduced deployment targets by 3 versions
- Modified `Converter#renderedRequestPath` to support iOS 13
Deployment target will be reduced by 3 versions.
- Resolves https://github.com/apple/swift-openapi-generator/issues/62
- Paired with https://github.com/apple/swift-openapi-generator/pull/63

Reduce deployment targets by 3 versions

---

Sources/OpenAPIRuntime/Interface/ClientTransport.swift

The example for `ClientMiddleware` doesn't compile
Correct the variable name in `ClientMiddleware`
The example can now compile

Correct variable name in `ClientMiddleware` reference documentation

---

Sources/OpenAPIRuntime/Conversion/Converter+Common.swift
Sources/OpenAPIRuntime/Conversion/Converter+Server.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Client.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Common.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift

`getRequiredRequestBodyAsText` currently returns `C?` instead of `C`. As the value should be required an optional in the return is causing issues.
The errors are `Cannot convert value of type 'C?' to specified type` and `Cannot infer contextual base in reference to member 'text'`
Change the return type of `getRequiredRequestBodyAsText`
Code using a required requestBody now compiles without errors.

Converter SPI methods for required fields should return non-optional types

---

Sources/OpenAPIRuntime/Conversion/Converter.swift
scripts/check-for-breaking-api-changes.sh

We want to know when we are making breaking changes to our public API.
Add a script that wraps `swift package diagnose-api-breaking-changes` which we'll start to use in CI. 
A script can be used to validate the current repo state against a baseline repo and treeish for breaking API changes.
Running this script produces the following output:
```console
❯ BASELINE_REPO_URL=https://github.com/apple/swift-openapi-runtime BASELINE_TREEISH=main bash scripts/check-for-breaking-api-changes.sh
** Checking required environment variables...
** Fetching baseline: https://github.com/apple/swift-openapi-runtime#main...
From https://github.com/apple/swift-openapi-runtime
* branch            main       -> FETCH_HEAD
** Checking for API changes since https://github.com/apple/swift-openapi-runtime#main …
```

Add check-for-breaking-api-changes.sh script

---

docker/docker-compose.yaml
scripts/soundness.sh

Like many other projects, we have a soundness script which runs in CI. It started out with some fast policy and style tests but has grown over time. It currently has:
1. Check for broken symlinks
2. Check for unacceptable language
3. Check all files have a license headers
4. Run swift-format lint
5. Check DocC compiliation has no warnings
6. Run integration test
On my machine, (5) takes 11s and (6) takes 1m13s.
The soundness script should be cheap to run so as not to disclosure running it often—potentially even adding it to a precommit hook.
Removing (5) and (6) from the soundness suite means it takes 3s, which is more reasonable.
- Add `integration-test` to Compose file.
- Add `docc-test` to Compose file.
- Stop running DocC and integration tests in `soundness.sh`.
Running `soundness.sh` …

Move DocC and integration tests into separate CI pipelines

---

Package.swift
Sources/OpenAPIRuntime/Base/OpenAPIValue.swift
Sources/OpenAPIRuntime/Conversion/CodableExtensions.swift
Sources/OpenAPIRuntime/Conversion/Configuration.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Sources/OpenAPIRuntime/Errors/ClientError.swift
Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Sources/OpenAPIRuntime/Errors/ServerError.swift
Sources/OpenAPIRuntime/Interface/UniversalClient.swift
Sources/OpenAPIRuntime/Interface/UniversalServer.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_CodableExtensions.swift

As a follow-on to https://github.com/apple/swift-openapi-generator/pull/99, let's also enable explicit existential any in the runtime library.
Enabled the flag in Package.swift (for Swift 5.9 and newer) and updated all the usage sites.
The codebase is closer to being ready for Swift 6.
Updated unit tests as well, all is passing locally.

Adopt explicit existential any

---

Sources/OpenAPIRuntime/Conversion/FoundationExtensions.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_CodableExtensions.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

Move to a consistent style when initializing local variables, always use `let foo = Foo(...)` vs `let foo: Foo = .init(...)`.
Updated all occurrences of the latter to use the former.
Consistent local variable initialization.
All tests passed.

[Runtime] Consistent style for initializing local variables

---

Sources/OpenAPIRuntime/Conversion/CurrencyExtensions.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated_RedactedHeaderFields.swift
Sources/OpenAPIRuntime/Interface/CurrencyTypes.swift
Tests/OpenAPIRuntimeTests/Deprecated/Test_Deprecated_RedactedHeaderFields.swift

For details, see https://github.com/apple/swift-openapi-generator/issues/113.
This PR deprecates the feature in the current 0.1.x version, so that it can be removed in 0.2.0.
When adopters use this feature in 0.1.x, they will get a deprecation warning.
Moved the tests to the deprecated section as well, to be removed before we tag 0.2.0.

Deprecate redactedHeaderFields

---

Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift

Two new OpenAPIValue tests were using a different style, and had some repetition around encoding/decoding.
Fixed up by bringing them to the same style as other OpenAPIValue tests.
Consistent style of tests, less code and easier to read.
All tests passed.

[Test] Make new OpenAPIValue tests consistent with the rest

---

Sources/OpenAPIRuntime/Conversion/Converter+Client.swift
Sources/OpenAPIRuntime/Conversion/Converter+Server.swift
Sources/OpenAPIRuntime/Conversion/CurrencyExtensions.swift
Sources/OpenAPIRuntime/Conversion/FoundationExtensions.swift
Sources/OpenAPIRuntime/Conversion/ParameterStyles.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Client.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_FoundationExtensions.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/52.
By default, query items are encoded as exploded (`key=value1&key=value2`), but OpenAPI allows explicitly requesting them unexploded (`key=value1,value2`). This feature missing has shown up in a few OpenAPI documents recently.
Add support for unexploded query items by expanding the helper functions and allow passing in `style` and `explode` parameters. The `style` is in preparation of also supporting alternative styles, but for now we just validate that only the supported style is provided.
Generated code can use these improved helper functions to encode/decode unexploded query items.
Updated/added unit tests for unexploded query items.

[Runtime] Support unexploded query items

---

Sources/OpenAPIRuntime/Conversion/ErrorExtensions.swift

Runtime side of https://github.com/apple/swift-openapi-generator/pull/205
Added a helper function that produces the right error.
Generated code can use this error to throw when an unknown case is encountered.
Tested together with the generator.

[Runtime] Stop generating an undocumented case for enums/oneOfs

---

Sources/OpenAPIRuntime/Base/CommonOutputPayloads.swift
Sources/OpenAPIRuntime/Base/OpenAPIValue.swift
Sources/OpenAPIRuntime/Conversion/CodableExtensions.swift
Sources/OpenAPIRuntime/Interface/CurrencyTypes.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/210.
Types conforming to `Hashable` do not need to explicity declare that they conform to `Equatable`. 
With this pull request, we are removing the explicit `Equatable` conformance of types already conforming to `Hashable` in the code base.
Types conforming to `Hashable` do explicitly declare a redundant conformance to `Equatable`.
N/A

Remove redundant explicit Equatable conformances

---

Sources/OpenAPIRuntime/StringCoder/StringDecoder.swift
Sources/OpenAPIRuntime/StringCoder/StringEncoder.swift
Tests/OpenAPIRuntimeTests/StringCoder/Test_StringCodingRoundtrip.swift

A sibling PR to https://github.com/apple/swift-openapi-runtime/pull/41, as part of moving from hand-crafted code that uses `LosslessStringConvertible` conformances on built-in and generated types, we need not just an URI coder, but also a raw string coder.
This will be used for encoding and decoding `text/plain` bodies, where only primitive types can be used, and are encoded as raw strings.
Introduced two types, `StringEncoder` and `StringDecoder`. It's very simple, doesn't support containers, only primitive types.
Once this lands, it'll allow us to get rid of our ugly marker protocols `_StringConvertible` and `_AutoLosslessStringConvertible` and always go through `Codable`. More on this in subsequent PRs integrating this logic.
Added a rountrip unit test.

Introduce StringEncoder and StringDecoder types

---

Sources/OpenAPIRuntime/Conversion/Converter+Server.swift
Sources/OpenAPIRuntime/Conversion/CurrencyExtensions.swift
Sources/OpenAPIRuntime/URICoder/Decoding/URIDecoder.swift
Sources/OpenAPIRuntime/URICoder/Decoding/URIValueFromNodeDecoder.swift
Sources/OpenAPIRuntime/URICoder/Encoding/URIEncoder.swift
Sources/OpenAPIRuntime/URICoder/Encoding/URIValueToNodeEncoder+Single.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift
Tests/OpenAPIRuntimeTests/URICoder/Decoder/Test_URIDecoder.swift
Tests/OpenAPIRuntimeTests/URICoder/Test_URICodingRoundtrip.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/249.
Adds a `decodeIfPresent` method on `URIDecoder` now used by the optional query param getter.
This makes the query param getter return nil instead of throwing an error when it encounters a missing optional query param.
Added new unit tests, hopefully these cover it now.

Fix optional query param parsing

---

Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift

While investigating https://github.com/apple/swift-openapi-generator/issues/251 I noticed we don't have a test case for an escaped path component.
Added an extra test case.
Unescaping path params has better test coverage.
This whole PR is about improving the tests.

Add an escaped path component test case

---

Sources/OpenAPIRuntime/Conversion/CodableExtensions.swift
Sources/OpenAPIRuntime/URICoder/Decoding/URIValueFromNodeDecoder+Single.swift
Sources/OpenAPIRuntime/URICoder/Decoding/URIValueFromNodeDecoder.swift
Sources/OpenAPIRuntime/URICoder/Encoding/URIValueToNodeEncoder+Single.swift
Sources/OpenAPIRuntime/URICoder/Encoding/URIValueToNodeEncoder.swift
Tests/OpenAPIRuntimeTests/URICoder/Test_URICodingRoundtrip.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/263.
Makes URIEncoder/URIDecoder able to handle custom Codable types in a single value container.
For more details check out the associated generator [PR](https://github.com/apple/swift-openapi-generator/pull/271).
More Codable types can be handled.
Updated unit tests.

[Runtime] Fix nested coding

---

Sources/OpenAPIRuntime/Conversion/Converter+Server.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Client.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Common.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift

In the previous PR, we missed one method which was supposed to be public, but was internal. Discovered while testing the generator, this this isn't being seen by users yet, but blocks us from rolling out the next 0.2.x generator.
Removed `@testable` (which made us miss it) from converter tests and made the missing method public.
Generated code should compile again.
This PR is mostly about updating tests to catch this next time.

[Bug] Make a missing converter helper public

---

Sources/OpenAPIRuntime/Errors/RuntimeError.swift

The review period for SOAR-0007 (Shorthand APIs for inputs and outputs) has now concluded. This pull request adds the required SPIs to the runtime library to throw a runtime error when the response and/or body does not match that of the shorthand API being used.
For further context, please review the proposal itself.[^1] 
[^1]: https://github.com/apple/swift-openapi-generator/pull/291
- Extend `internal enum RuntimeError: Error` with two new cases:
- `.unexpectedResponseStatus(expectedStatus:response:)`
- `.unexpectedResponseBody(expectedContent:body:)`
- Add SPI for generated code, to throw these errors:
- `@_spi(Generated) public throwUnexpectedResponseStatus(expectedStatus:response:)`
- `@_spi(Generated) public throwUnexpectedResponseBody(expectedStatus:body:)`
Runtime library has two …

Add SPIs for throwing RuntimeError from shorthand generated APIs

---

Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

OpenAPI supports base64-encoded data but to this point OpenAPI Generator has not (https://github.com/apple/swift-openapi-generator/issues/11).
Introduce the `Base64EncodedData` codable type to allow users in the generator to describe byte types which must be en/de-coded.
Users will be able to describe base64-encoded data as `OpenAPIRuntime.Base64EncodedData` e.g.
```
public typealias MyData = OpenAPIRuntime.Base64EncodedData
```
Added a round-trip encode/decode test `testEncodingDecodingRoundTrip_base64_success`

Support base64-encoded data

---

Sources/OpenAPIRuntime/Base/CopyOnWriteBox.swift
Tests/OpenAPIRuntimeTests/Base/Test_CopyOnWriteBox.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

Runtime changes for https://github.com/apple/swift-openapi-generator/issues/70.
Introduce a new wrapper type `CopyOnWriteBox` as a reference type with copy-on-write semantics, to be used by the generated code to hide a ref type inside a struct that needs boxing. (Details on the logic will be in the generator PR description.)
A new type available for the generated code to use for breaking reference cycles.
Added unit tests for the type.

[Runtime] Support recursive types

---

Sources/OpenAPIRuntime/Conversion/ParameterStyles.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Deprecated/Test_Deprecated.swift
Tests/OpenAPIRuntimeTests/Interface/Test_HTTPBody.swift
Tests/OpenAPIRuntimeTests/Interface/Test_UniversalServer.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift
Tests/OpenAPIRuntimeTests/URICoder/Test_URICodingRoundtrip.swift
docker/Dockerfile

Let's move to swift-format 5.9, as per https://github.com/apple/swift-openapi-generator/issues/175.
Bump to 5.9 and update code to pass, also update the Dockerfile for Linux CI.
Uses swift-format 5.9.
Soundness passed.

Bump swift-format to 5.9

---

Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Sources/OpenAPIRuntime/Errors/ClientError.swift
Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Sources/OpenAPIRuntime/Errors/ServerError.swift
Sources/OpenAPIRuntime/Interface/UniversalClient.swift
Sources/OpenAPIRuntime/Interface/UniversalServer.swift
Tests/OpenAPIRuntimeTests/Interface/Test_UniversalClient.swift
Tests/OpenAPIRuntimeTests/Interface/Test_UniversalServer.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/302 and https://github.com/apple/swift-openapi-generator/issues/17.
The issue was that we hid away errors thrown in transports and middlewares, and the adopter would get `ClientError` where the `underlyingError` wasn't the error thrown by the underlying transport/middleware, but instead a private wrapper of ours.
Make sure `{Client,Server}Error.underlyingError` contains the error thrown from the underlying transport/middleware when that was the cause of the error, otherwise keep `RuntimeError` there as was the behavior until now.
Also added a `causeDescription` property on both public error types to allow communicating the context for the underlying error.
Also made sure middleware errors are now wrapped in Client/ServerError, …

Improved enriched error propagation from the transport and middlewares

---

docker/docker-compose.2204.main.yaml

Same as https://github.com/apple/swift-openapi-generator/pull/353 but for the runtime package.
Disable warnings as errors on CI for nightlies.
_[After your change, what will change.]_
CI should pass again.

Disable warnings-as-errors for nightlies

---

Sources/OpenAPIRuntime/Base/OpenAPIMIMEType.swift
Sources/OpenAPIRuntime/Conversion/Converter+Common.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIMIMEType.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Common.swift

The runtime changes for https://github.com/apple/swift-openapi-generator/issues/315.
- Introduces a new SPI method `Converter.bestContentType` that takes a received content type value and from a provided list of other content types, picks the most appropriate one. This actually follows the specification now, by going from most specific (including parameter matching) to least specific (most wildcard-y).
- Deprecates the previously used methods `Converter.makeUnexpectedContentTypeError` and `Converter.isMatchingContentType`.
SPI methods that the generated code can use to correctly match content types.
Added unit tests.

[Runtime] Improved content type matching

---

Sources/OpenAPIRuntime/Conversion/CodableExtensions.swift
Sources/OpenAPIRuntime/Conversion/ErrorExtensions.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Tests/OpenAPIRuntimeTests/URICoder/Test_URICodingRoundtrip.swift

The runtime changes to address https://github.com/apple/swift-openapi-generator/issues/275.
This makes debugging of decoding of oneOf/anyOf much easier, as the individual errors aren't dropped on the floor anymore.
Added SPI that allows the generated code to collect and report partial errors when a oneOf/anyOf fails to decode (that includes trying multiple subschemas, which themselves emit errors when they're not the right match).
Easier debugging of oneOf/anyOf decoding issues.
Tested manually as part of the generator changes, we don't generally test exact error strings.

[Runtime] Include partial errors in oneOf/anyOf decoding errors

---

Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift

- Fixes [#369](https://github.com/apple/swift-openapi-generator/issues/368)
- Remove init label argument from Base64EncodedData
- The Base64EncodedData init will be called without the label.
- Adjust some tests from Test_OpenAPIValue

Base64EncodedData initializer taking an array slice shouldn't have a label

---

NOTICE.txt
Sources/OpenAPIRuntime/Multipart/ByteUtilities.swift
Sources/OpenAPIRuntime/Multipart/MultipartBytesToFramesSequence.swift
Sources/OpenAPIRuntime/Multipart/MultipartInternalTypes.swift
Sources/OpenAPIRuntime/Multipart/MultipartParser.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartBytesToFramesSequence.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartParser.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

Start landing the parts of the multipart machinery that is unlikely to change as part of the multipart proposal that's finishing review tomorrow.
Introduce a bytes -> frames parser and an async sequence that wraps it.
A "frame" is either the full header fields section or a single chunk of a part body.
We can now frame bytes of a multipart body.
Added unit tests for the state machine, the parser, and the async sequence.

[Multipart] Introduce a bytes -> frames parser

---

Sources/OpenAPIRuntime/Base/ContentDisposition.swift
Sources/OpenAPIRuntime/Multipart/MultipartPublicTypesExtensions.swift
Sources/OpenAPIRuntime/Multipart/MultipartValidation.swift
Tests/OpenAPIRuntimeTests/Base/Test_ContentDisposition.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartValidationSequence.swift

The OpenAPI document provides information about which parts are required, optional, arrays, and single values, so we need to enforce those semantics for the adopter, just like we enforce (using JSONDecoder) that a received JSON payload follows the documented structure.
Since the mutlipart body is not a struct, but an async sequence of parts, it's a little more complicated.
We introduce a `MultipartValidationSequence` with a state machine that keeps track of the requirements and which of them have already been fulfilled over time. And it throws an error if any of the requirements are violated.
For missing required parts, the error is thrown when `nil` is received from the upstream sequence, indicating that there will be no more parts coming.
To implement this, an internal type …

[Multipart] Validation sequence

---

Sources/OpenAPIRuntime/Interface/HTTPBody.swift
Sources/OpenAPIRuntime/Multipart/MultipartFramesToRawPartsSequence.swift

The associated value of  enum case `HTTPBody.Length.known` was `Int`, and, on watchOS, `Int = Int32`, which is not ideal for a content length.
- (API breaking) Change type of HTTPBody.Length.known from Int to Int64.
Can now express larger values for content type on 32-bit platforms.
Unit tests pass.
- Fixes https://github.com/apple/swift-openapi-generator/issues/354.
I have marked this PR as `semver/major` as it constitutes the first of the PRs we make in the run up to 1.0.0-alpha.1 and the release notes generator should therefore catch us from inadvertently cutting another pre-1.0 patch release.

Change type of HTTPBody.Length.known from Int to Int64

---

Package.swift

While this isn't technically necessary, as all versions of a platform not explicitly mentioned are assumed to be supported, it's better to be explicit here.
Add `visionOS(.v1)` to the list of supported platforms.
Clearer support matrix.
N/A, this is basically just a documentation change.

Add visionOS platform support

---

Sources/OpenAPIRuntime/Base/UndocumentedPayload.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift

The runtime changes for https://github.com/apple/swift-openapi-generator/issues/299.
Added `headerFields` and `body` properties to `UndocumentedPayload`, allowing adopters to access the full request information when an undocumented response is returned.
Easier access to the raw payload when an undocumented response is returned.
These are just the runtime changes, tested together with generated changes.

[Runtime] Add headerFields and body to UndocumentedPayload

---

Sources/OpenAPIRuntime/Conversion/CurrencyExtensions.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Client.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift

A surprising oversight, we were never setting the `content-length` header when sending out a known-length body.
Some transports might be already doing this, but this change makes things more consistent.
Add the `content-length` header when setting a body and we know the length from the `HTTPBody`.
More consistent experience.
Adapted unit tests.

Set content-length in request/response bodies if known

---

Sources/OpenAPIRuntime/Conversion/CodableExtensions.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/525.
Turns out that the mere act of creating a decoding container is meaningful and we skipped it as an optimization, causing JSONDecoder to fail for empty dictionaries when used in additional properties.
Remove the extra guards that skipped creating a container, even when we already know there are no elements.
No more failures when encoding empty dictionaries in additionalProperties.
Tested manually as this requirement seems to be coming out of JSONDecoder.

Fix empty additionalProperties dictionary encoding

---

Sources/OpenAPIRuntime/Base/OpenAPIMIMEType.swift
Sources/OpenAPIRuntime/Conversion/Configuration.swift
Sources/OpenAPIRuntime/Conversion/Converter+Client.swift
Sources/OpenAPIRuntime/Conversion/Converter+Server.swift
Sources/OpenAPIRuntime/Conversion/CurrencyExtensions.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Client.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Server.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

See [apple/swift-openapi-generator#556](https://github.com/apple/swift-openapi-generator/issues/556) for more.
Add converter methods for encoding and decoding XML request and response body.
Add `CustomCoder` protocol, allows to use other `Encoder` and `Decoder` for other `content-type` body.
User can define custom coder, and assign a custom coder to a specific content-type within `Configuration.customCoders` dictionary.
It's now possible to define custom encoder and decoder for supported content-type.
Added converter methods are tested with a mock custom coder for `application/xml` content-type. To avoid adding a dependency to a XMLCoder like [CoreOffice/XMLCoder](https://github.com/CoreOffice/XMLCoder), mock custom coder uses JSONEncoder and JSONDecoder.
Encoding and decoding to XML are …

Add support for application/xml body

---

Sources/OpenAPIRuntime/Conversion/Converter+Common.swift
Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Common.swift

When the server response has a content-type header that does not conform to the OpenAPI document, we currently throw an error. However, this error presents itself in a very confusing manner: it prints `Unexpected Content-Type header: application/json`, where `application/json is the _expected_ content-type. At best, this is ambiguous and potentially misleading.
- Extend `case RuntimeError.unexpectedContentTypeHeader` with _both_ the expected and received content-type associated values.
- Update the printed description to include both the expected and received content-type header values.
When an unexpected content-type is received, the error message is clearer.
Updated the existing test that expects an error to check the error and that the error values are provided in the correct order.

Improve error message when encountering unexpected content-type headers

---

Sources/OpenAPIRuntime/Base/OpenAPIMIMEType.swift
Tests/OpenAPIRuntimeTests/Base/Test_ContentDisposition.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIMIMEType.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Converter+Common.swift
Tests/OpenAPIRuntimeTests/EventStreams/Test_ServerSentEventsDecoding.swift
Tests/OpenAPIRuntimeTests/EventStreams/Test_ServerSentEventsEncoding.swift
Tests/OpenAPIRuntimeTests/Interface/Test_HTTPBody.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift
Tests/OpenAPIRuntimeTests/URICoder/Decoder/Test_URIValueFromNodeDecoder.swift
Tests/OpenAPIRuntimeTests/URICoder/Test_URICodingRoundtrip.swift

Fixes to get closer to building in Swift 6 mode without diagnostics.
- Made two public types Sendable
- s/#file/#filePath in tests
Builds with fewer warnings when trying Swift 6 mode (will open another PR for the remaining work).
Unit tests passed.

Swift 6 prep - Part 1

---

Sources/OpenAPIRuntime/Multipart/MultipartFramesToRawPartsSequence.swift

Fixing Issues with Building in Swift 6 for Linux
* Fix Issues with Upstream Iterator
Compatability with Swift 6 on Linux
TBD

Fixing Issues with Async Upstream

---

Sources/OpenAPIRuntime/Base/OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift

When receiving containers from adopter code, there might be NSNull values, which represent a nil value.
Previously, this value would not be treated as nil, instead it'd throw an error as an unrecognized type.
Handle NSNull and treat it as nil.
You can provide a container with an NSNull nested value and it'll get encoded correctly.
Added a unit test.

Support NSNull in OpenAPIContainer types

---

.gitignore
Sources/OpenAPIRuntime/Base/OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift

When getting CoreFoundation/Foundation types, especially numbers, they automatically bridge to Swift types like Bool, Int, etc. That casting is pretty flexible, and allows e.g. casting a number into a boolean, which isn't desired when encoding into JSON, as `false` and `0` represent very different values.
Previously, we relied on the automatic casting to know how to encode values, however that produced incorrect results in some cases.
Add explicit handling of CF/NS types and try to encode using that new method before falling back to testing for native Swift types. This ensures that the original intention of the creator of the CF/NS types doesn't get lost in encoding.
Correct encoding into JSON of types produced in the CF/NS world, like JSONSerialization.
Added unit tests.

Improved encoding of NSNumber in OpenAPIValueContainer

---

Sources/OpenAPIRuntime/Conversion/Configuration.swift
Sources/OpenAPIRuntime/Conversion/Converter.swift
Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Tests/OpenAPIRuntimeTests/Conversion/Test_Configuration.swift
Tests/OpenAPIRuntimeTests/Test_Runtime.swift

A second attempt at https://github.com/apple/swift-openapi-generator/issues/605, this time less open-ended than #111.
Only allow customizing the JSON encoding options.
- Added a `JSONEncodingOptions` option set.
- Added a corresponding property on the `Configuration` struct.
- Piped the value to the underlying JSONEncoder.
Allows users to customize the JSON encoding options.
Added unit tests.

Custom JSON encoding options

---

.github/workflows/pull_request.yml
.github/workflows/scheduled.yml
.licenseignore
.swiftformatignore
scripts/check-for-breaking-api-changes.sh
scripts/check-for-broken-symlinks.sh
scripts/check-for-docc-warnings.sh
scripts/check-for-unacceptable-language.sh
scripts/check-license-headers.sh
scripts/generate-contributors-list.sh
scripts/run-integration-test.sh
scripts/run-swift-format.sh
scripts/soundness.sh

Following on from the migration in Swift OpenAPI Generator, we need to migrate this repo to GitHub Actions based CI and the reusable workflows that are currently in the NIO repo. 
In order to bootstrap the migration, we need to merge the workflows in, otherwise we won't get any PR feedback on them while we get them ready. As a practical matter, they are all passing locally (verified) by `act` but it would be nice to stage these in so we can keep a green CI while we migrate and decommission the old CI.
So this disables the soundness checks for now, so we can then use a follow up PR to do the cut over with testing in the PR.
Old CI still working, new CI should start running in some capacity.

ci: Migrate to GitHub Actions and reusable workflows, part one

---

Sources/OpenAPIRuntime/URICoder/Common/URIEncodedNode.swift
Sources/OpenAPIRuntime/URICoder/Parsing/URIParser.swift
Sources/OpenAPIRuntime/URICoder/Serialization/URISerializer.swift
Tests/OpenAPIRuntimeTests/URICoder/Decoder/Test_URIValueFromNodeDecoder.swift
Tests/OpenAPIRuntimeTests/URICoder/Encoding/Test_URIValueToNodeEncoder.swift
Tests/OpenAPIRuntimeTests/URICoder/Parsing/Test_URIParser.swift
Tests/OpenAPIRuntimeTests/URICoder/Serialization/Test_URISerializer.swift

It's a useful pattern to define a single JSON schema for all your (e.g. query) parameters, and handle them as a single object in your code.
In OpenAPI, that'd be expressed like this, for example:
```yaml
name: myParams
in: query
explode: true
style: form
schema:
$ref: '#/components/schemas/QueryObject'
QueryObject:
type: object
properties:
myString:
type: string
myList:
type: array
items:
type: string
```
Until now, the `myList` property would not be allowed, and would fail to serialize and parse, as arrays within objects were not allowed for `form` style parameters (used by query items, by default).
This PR extends the support of the `form` style to handle single nesting in the top level objects. It does _not_ add support for arbitrarily deep nesting.
As part of this work, we also now …

Support nested arrays of primitive values inside of objects

---

Sources/OpenAPIRuntime/Deprecated/Deprecated.swift
Sources/OpenAPIRuntime/EventStreams/ServerSentEventsDecoding.swift
Tests/OpenAPIRuntimeTests/EventStreams/Test_ServerSentEventsDecoding.swift

As discussed in https://github.com/apple/swift-openapi-generator/issues/622, some APIs, e.g., ChatGPT or Claude, may return a non-JSON byte sequence to terminate a stream of events.
If not handled with a workaround (see below)such non-JSON terminating byte sequences cause a decoding error.
This PR adds the ability to customise the terminating byte sequence by providing a closure to `asDecodedServerSentEvents()` as well as `asDecodedServerSentEventsWithJSONData()` that can match incoming data for the terminating byte sequence before it is decoded into JSON, for instance.
Instead of having to decode and re-encode incoming events to filter out the terminating byte sequence - as seen in https://github.com/apple/swift-openapi-generator/issues/622#issuecomment-2346391088 - terminating byte …

EventStreams: Customisable Terminating Byte Sequence

---

.github/workflows/scheduled.yml

This was copied in from the generator repo but there aren't examples in this repo so the job is failing.
Remove this job from the scheduled workflow. 
Scheduled workflow should now pass fully. 
None.

ci: Remove examples pipeline from scheduled workflow

---

.github/workflows/pull_request.yml
.github/workflows/scheduled.yml
.spi.yml
Sources/OpenAPIRuntime/EventStreams/ServerSentEventsDecoding.swift

We just updated our CI matrix in NIO to only support 5.9, 5.10 and 6.
This PR updates the trigger files in this repo. Since this repo was always 5.9+ this is easy.
Up to date CI

[CI] Update to Swift 6 CI

---

Sources/OpenAPIRuntime/Interface/ErrorHandlingMiddleware.swift
Tests/OpenAPIRuntimeTests/Interface/Test_ErrorHandlingMiddleware.swift

Implementation of [Improved error handling proposal](https://forums.swift.org/t/proposal-soar-0011-improved-error-handling/74736)
Added HTTPResponseConvertible protocol
Added ErrorHandlingMiddleware that converts errors confirming to HTTPResponseConvertible to a HTTP response.
The new middleware is an opt-in middleware. So there won't be any change to existing clients.
Clients who wish to have OpenAPI error handling can include the new error middleware in their application.
Added E2E tests to test the new middleware.

Add error handling middleware

---

Sources/OpenAPIRuntime/Errors/RuntimeError.swift
Tests/OpenAPIRuntimeTests/Errors/Test_RuntimeError.swift

https://github.com/apple/swift-openapi-generator/issues/609#issuecomment-2522503704
Confirm `RuntimeError` to `HTTPResponseConvertible` and provide granular status codes.
Response codes for bad user input will be 4xx (instead of 500)
Unit tests.

Conform RuntimeError to HTTPResponseConvertible

---

.github/workflows/pull_request.yml
Sources/OpenAPIRuntime/Base/Acceptable.swift
Sources/OpenAPIRuntime/Base/ContentDisposition.swift
Sources/OpenAPIRuntime/Interface/CurrencyTypes.swift
Sources/OpenAPIRuntime/Multipart/MultipartBoundaryGenerator.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartBytesToFramesSequence.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartFramesToBytesSequence.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartFramesToRawPartsSequence.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartRawPartsToFramesSequence.swift
Tests/OpenAPIRuntimeTests/Multipart/Test_MultipartValidationSequence.swift

PR CI was missing testing with nighly Linux toolchains from main.
Enable nightly toolchain CI as well.
More test coverage on PRs.
See this PR's CI if this works or if we need more changes.

[CI] Enable Linux nightly main on PRs

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
Sources/OpenAPIRuntime/Base/OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift

CoreFoundation isn't API on Windows, so compile it out in that case. All tests pass with these changes.

Add support for Windows

---

.github/workflows/main.yml

Move nightly disable parameter in main.yml - the matrix workflow doesn't accept this parameter, it's in the wrong place. It's already in the correct place in the pull request yaml.

move nightly disable parameter in main.yml

---

.github/workflows/main.yml

Add /swift-openapi-runtime as safe directory. This is already set in the pull request yaml but is missing here

main.yml - add /swift-openapi-runtime as safe directory

---

Sources/OpenAPIRuntime/Conversion/ErrorExtensions.swift

Don't have typos in error messages.
Fixed the typo.
Typo no more.
N/A

Fix typo in MultiError

---

Sources/OpenAPIRuntime/Interface/ErrorHandlingMiddleware.swift
Sources/OpenAPIRuntime/Interface/ServerTransport.swift
Sources/OpenAPIRuntime/Interface/UniversalServer.swift
Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
Tests/OpenAPIRuntimeTests/Interface/Test_ErrorHandlingMiddleware.swift
Tests/OpenAPIRuntimeTests/URICoder/Parsing/Test_URIParser.swift

Formatter got upgraded upstream, so we need to update formatting in our project.
Regenerated using swift-format from Swift 6.2 and made a few manual fixes.
Soundness format is clean again.
Ran locally.

Fix formatting in swift-format 6.2
